/**
 * T LEARN PRO - Full Curriculum Data
 * HTML, CSS, JavaScript, Python — Beginner to Intermediate
 */

const curriculumData = {

  HTML: {
    icon: 'fa-html5',
    topics: [
      { title: 'What is HTML', theory: 'HTML (HyperText Markup Language) is the standard language for creating web pages. It describes the structure of a page using elements represented by tags.', challenge: 'Write a basic HTML page with a title and one paragraph.', snippet: `<!DOCTYPE html>\n<html>\n  <head><title>My Page</title></head>\n  <body><p>Hello World</p></body>\n</html>` },
      { title: 'How the Web Works', theory: 'When you visit a URL, your browser sends a request to a server. The server responds with HTML, CSS, and JS files that the browser renders into a visual page.', challenge: 'Explain the request-response cycle in your own words.', snippet: `Browser → HTTP Request → Server\nServer → HTML/CSS/JS → Browser\nBrowser renders the page` },
      { title: 'HTML Document Structure', theory: 'Every HTML document starts with <!DOCTYPE html>, followed by <html>, <head> (metadata), and <body> (visible content).', challenge: 'Create a valid HTML document with head and body sections.', snippet: `<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8">\n    <title>Document</title>\n  </head>\n  <body>\n    <!-- Content here -->\n  </body>\n</html>` },
      { title: 'Elements, Tags & Attributes', theory: 'HTML elements are made of opening and closing tags. Attributes provide extra info inside the opening tag, like id, class, or href.', challenge: 'Add an id and class attribute to a div element.', snippet: `<div id="main" class="container">\n  <p>Content here</p>\n</div>` },
      { title: 'Headings & Paragraphs', theory: 'Headings go from h1 (most important) to h6 (least important). Paragraphs use <p> tags. Use headings to structure your content hierarchy.', challenge: 'Create a page with h1, h2, and a paragraph.', snippet: `<h1>Main Title</h1>\n<h2>Subtitle</h2>\n<p>This is a paragraph of text.</p>` },
      { title: 'Lists', theory: '<ul> creates unordered (bullet) lists. <ol> creates ordered (numbered) lists. <dl> creates description lists. Each item uses <li>.', challenge: 'Create both an ordered and unordered list.', snippet: `<ul>\n  <li>Apples</li>\n  <li>Bananas</li>\n</ul>\n<ol>\n  <li>First</li>\n  <li>Second</li>\n</ol>` },
      { title: 'Links & Anchor Tags', theory: 'The <a> tag creates hyperlinks. The href attribute specifies the URL. Use target="_blank" to open in a new tab.', challenge: 'Create a link to google.com that opens in a new tab.', snippet: `<a href="https://google.com" target="_blank">Visit Google</a>` },
      { title: 'Images', theory: 'The <img> tag displays images. It is self-closing. The src attribute points to the image URL and alt provides alternative text for accessibility.', challenge: 'Add an image with a descriptive alt attribute.', snippet: `<img src="photo.jpg" alt="A mountain landscape" width="400">` },
      { title: 'Audio & Video', theory: 'HTML5 introduced <audio> and <video> tags for native media. Use the controls attribute to show play/pause buttons. Provide multiple source formats for compatibility.', challenge: 'Embed a video with controls.', snippet: `<video controls width="600">\n  <source src="movie.mp4" type="video/mp4">\n  Your browser does not support video.\n</video>` },
      { title: 'Div and Span', theory: '<div> is a block-level container for grouping elements. <span> is an inline container for styling portions of text. Neither has semantic meaning.', challenge: 'Wrap a paragraph in a div and highlight a word with span.', snippet: `<div class="box">\n  <p>This is <span class="highlight">important</span> text.</p>\n</div>` },
      { title: 'Semantic HTML', theory: 'Semantic tags like <header>, <nav>, <main>, <section>, <article>, <aside>, and <footer> describe the meaning of content, improving accessibility and SEO.', challenge: 'Build a page layout using only semantic tags.', snippet: `<header><nav>Menu</nav></header>\n<main>\n  <section><article>Post</article></section>\n  <aside>Sidebar</aside>\n</main>\n<footer>Footer</footer>` },
      { title: 'Tables', theory: 'Tables display tabular data. <table> wraps everything. <thead> holds headers, <tbody> holds data rows. Each row is <tr>, headers are <th>, data cells are <td>.', challenge: 'Create a 3-column table with headers.', snippet: `<table>\n  <thead>\n    <tr><th>Name</th><th>Age</th><th>City</th></tr>\n  </thead>\n  <tbody>\n    <tr><td>Alice</td><td>25</td><td>Lagos</td></tr>\n  </tbody>\n</table>` },
      { title: 'Forms Basics', theory: 'Forms collect user input. The <form> tag wraps inputs. The action attribute specifies where data is sent. The method attribute is GET or POST.', challenge: 'Create a basic login form.', snippet: `<form action="/login" method="POST">\n  <input type="email" name="email" placeholder="Email">\n  <input type="password" name="pass" placeholder="Password">\n  <button type="submit">Login</button>\n</form>` },
      { title: 'Input Types', theory: 'HTML5 offers many input types: text, email, password, number, date, checkbox, radio, file, range, color. Each gives the browser hints for validation and mobile keyboards.', challenge: 'Create a form with 5 different input types.', snippet: `<input type="text" placeholder="Name">\n<input type="email" placeholder="Email">\n<input type="number" min="0" max="100">\n<input type="date">\n<input type="checkbox"> Accept terms` },
      { title: 'Form Validation', theory: 'HTML5 built-in validation uses attributes like required, minlength, maxlength, pattern, min, and max. The browser shows error messages automatically.', challenge: 'Add required and minlength validation to a form.', snippet: `<input type="text" required minlength="3" placeholder="Username">\n<input type="email" required placeholder="Email">\n<button type="submit">Submit</button>` },
      { title: 'Meta Tags & SEO', theory: 'Meta tags in <head> provide metadata. The description meta tag helps SEO. The viewport meta tag controls mobile display. og: tags control social media previews.', challenge: 'Add essential meta tags to your page head.', snippet: `<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<meta name="description" content="My awesome page">\n<meta property="og:title" content="Page Title">` },
      { title: 'Accessibility & ARIA', theory: 'ARIA (Accessible Rich Internet Applications) attributes help screen readers understand your UI. Use role, aria-label, aria-hidden, and alt text for images to make sites accessible.', challenge: 'Add ARIA labels to a navigation menu.', snippet: `<nav aria-label="Main navigation">\n  <ul role="list">\n    <li><a href="/" aria-current="page">Home</a></li>\n    <li><a href="/about">About</a></li>\n  </ul>\n</nav>` },
    ]
  },

  CSS: {
    icon: 'fa-css3-alt',
    topics: [
      { title: 'What is CSS', theory: 'CSS (Cascading Style Sheets) controls the visual presentation of HTML. It separates content from design. Styles can be inline, internal (in <style>), or external (in a .css file).', challenge: 'Link an external CSS file to your HTML page.', snippet: `<!-- In HTML head -->\n<link rel="stylesheet" href="styles.css">\n\n/* In styles.css */\nbody {\n  background: #1a1a2e;\n  color: white;\n}` },
      { title: 'Selectors', theory: 'CSS selectors target elements to style. Element selectors target tag names. Class selectors use a dot (.). ID selectors use a hash (#). Specificity determines which rule wins.', challenge: 'Write selectors for an element, class, and ID.', snippet: `p { color: blue; }          /* element */\n.card { padding: 20px; }    /* class */\n#hero { font-size: 48px; }  /* ID */\np.intro { color: green; }   /* combined */` },
      { title: 'Colors & Units', theory: 'CSS colors can be named (red), hex (#ff0000), rgb(255,0,0), or hsl(0,100%,50%). Units include px (pixels), rem (root font size), em (parent size), % (relative), vw/vh (viewport).', challenge: 'Style a div using rem units and an HSL color.', snippet: `div {\n  color: hsl(220, 90%, 60%);\n  font-size: 1.5rem;\n  padding: 2rem;\n  width: 80%;\n  height: 50vh;\n}` },
      { title: 'The Box Model', theory: 'Every element is a box: content → padding → border → margin. Use box-sizing: border-box so padding and border are included in the element width, not added to it.', challenge: 'Create a card with padding, border, and margin.', snippet: `* { box-sizing: border-box; }\n\n.card {\n  width: 300px;\n  padding: 24px;\n  border: 1px solid #ddd;\n  margin: 16px;\n  border-radius: 8px;\n}` },
      { title: 'Display Property', theory: 'display controls how elements behave in layout. block takes full width and creates a new line. inline stays in text flow. inline-block combines both. none hides the element.', challenge: 'Change a span to display as a block element.', snippet: `span { display: block; }\ndiv { display: inline; }\n.hidden { display: none; }\n.inline-card { display: inline-block; width: 200px; }` },
      { title: 'Position', theory: 'static is the default. relative moves from its normal position. absolute positions relative to the nearest positioned ancestor. fixed is relative to the viewport. sticky sticks on scroll.', challenge: 'Position a badge in the top-right corner of a card.', snippet: `.card { position: relative; }\n.badge {\n  position: absolute;\n  top: -8px;\n  right: -8px;\n  background: red;\n  border-radius: 50%;\n}` },
      { title: 'Flexbox', theory: 'Flexbox is a one-dimensional layout system. Set display: flex on the parent. justify-content aligns on the main axis. align-items aligns on the cross axis. flex-wrap allows wrapping.', challenge: 'Center a div both horizontally and vertically.', snippet: `.container {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  gap: 16px;\n  flex-wrap: wrap;\n}` },
      { title: 'CSS Grid', theory: 'Grid is a two-dimensional layout system. Set display: grid on the parent. grid-template-columns defines columns. fr units distribute available space. gap controls spacing between cells.', challenge: 'Create a 3-column responsive grid.', snippet: `.grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 24px;\n}\n@media (max-width: 768px) {\n  .grid { grid-template-columns: 1fr; }\n}` },
      { title: 'Responsive Design & Media Queries', theory: 'Media queries apply styles based on screen size. Use mobile-first design: write base styles for mobile, then add breakpoints for larger screens with min-width.', challenge: 'Write a media query that changes font size on mobile.', snippet: `/* Mobile first */\nbody { font-size: 16px; }\n\n/* Tablet */\n@media (min-width: 768px) {\n  body { font-size: 18px; }\n}\n\n/* Desktop */\n@media (min-width: 1024px) {\n  body { font-size: 20px; }\n}` },
      { title: 'Backgrounds & Gradients', theory: 'CSS backgrounds can be solid colors, images, or gradients. linear-gradient() creates directional color transitions. radial-gradient() creates circular gradients. background-size: cover fills the element.', challenge: 'Create a hero section with a gradient background.', snippet: `.hero {\n  background: linear-gradient(135deg, #667eea, #764ba2);\n  /* or */\n  background: radial-gradient(circle, #1a1a2e, #0f3460);\n}` },
      { title: 'Shadows & Borders', theory: 'box-shadow adds shadows to elements. text-shadow adds shadows to text. border-radius rounds corners. You can create circles with border-radius: 50% on a square element.', challenge: 'Add a glowing shadow effect to a card.', snippet: `.card {\n  border-radius: 16px;\n  box-shadow: 0 4px 24px rgba(37, 99, 235, 0.3);\n}\n.avatar {\n  border-radius: 50%;\n  box-shadow: 0 0 0 3px #2563eb;\n}` },
      { title: 'Transitions', theory: 'Transitions smoothly animate property changes. Specify the property, duration, and easing function. Use transition: all for all properties. Common easing: ease, linear, ease-in-out.', challenge: 'Add a smooth color transition on button hover.', snippet: `button {\n  background: #2563eb;\n  transition: background 0.3s ease, transform 0.2s ease;\n}\nbutton:hover {\n  background: #1d4ed8;\n  transform: translateY(-2px);\n}` },
      { title: 'CSS Animations & Keyframes', theory: '@keyframes defines animation steps. The animation property applies it: name, duration, timing-function, delay, iteration-count. Use animation-fill-mode: forwards to keep the end state.', challenge: 'Create a pulsing animation for a loading indicator.', snippet: `@keyframes pulse {\n  0%, 100% { opacity: 1; transform: scale(1); }\n  50% { opacity: 0.5; transform: scale(0.95); }\n}\n.loader { animation: pulse 2s ease-in-out infinite; }` },
      { title: 'CSS Variables', theory: 'Custom properties (--variable-name) store reusable values. Define them in :root for global access. Reference with var(--name). They can be updated with JavaScript for dynamic theming.', challenge: 'Create a color theme using CSS variables.', snippet: `:root {\n  --primary: #2563eb;\n  --bg: #050b1d;\n  --text: #ffffff;\n}\n.btn {\n  background: var(--primary);\n  color: var(--text);\n}` },
      { title: 'Transform', theory: 'transform applies visual transformations without affecting layout. translate() moves, scale() resizes, rotate() spins, skew() slants. Combine multiple transforms in one property.', challenge: 'Create a card that lifts on hover using transform.', snippet: `.card {\n  transition: transform 0.3s ease;\n}\n.card:hover {\n  transform: translateY(-8px) scale(1.02);\n}` },
    ]
  },

  JavaScript: {
    icon: 'fa-js',
    topics: [
      { title: 'What is JavaScript', theory: 'JavaScript is a programming language that runs in the browser and on servers (Node.js). It makes web pages interactive — responding to clicks, fetching data, updating content without reloading.', challenge: 'Write a script that shows an alert when the page loads.', snippet: `// Runs when page loads\nwindow.onload = function() {\n  console.log('Page loaded!');\n  alert('Welcome to T-Learn Pro');\n};` },
      { title: 'Variables: var, let, const', theory: 'var is function-scoped and hoisted (avoid it). let is block-scoped and can be reassigned. const is block-scoped and cannot be reassigned (but objects/arrays can be mutated).', challenge: 'Declare variables using let and const appropriately.', snippet: `const API_URL = 'https://api.example.com'; // never changes\nlet count = 0;  // will change\ncount = 1;      // ok\n// API_URL = 'other'; // ERROR` },
      { title: 'Data Types', theory: 'JS has 8 types: String, Number, Boolean, null, undefined, Object, Symbol, BigInt. Use typeof to check. Strings use quotes, numbers are unquoted, booleans are true/false.', challenge: 'Create variables of 5 different data types.', snippet: `const name = "Alice";        // String\nconst age = 25;              // Number\nconst active = true;         // Boolean\nconst data = null;           // null\nlet result;                  // undefined\nconst user = { name, age };  // Object` },
      { title: 'Operators', theory: 'Arithmetic: + - * / % **. Comparison: === !== > < >= <=. Always use === (strict equality) not == (loose). Logical: && || !. Ternary: condition ? ifTrue : ifFalse.', challenge: 'Use the ternary operator to check if a number is even.', snippet: `const x = 10;\nconst isEven = x % 2 === 0 ? 'even' : 'odd';\nconsole.log(isEven); // 'even'\n\nconst a = true && false; // false\nconst b = true || false; // true` },
      { title: 'If/Else & Switch', theory: 'if/else runs code based on conditions. else if chains multiple conditions. switch is cleaner for checking one variable against many values. Always include a default case in switch.', challenge: 'Write a function that grades a score (A/B/C/F).', snippet: `function grade(score) {\n  if (score >= 90) return 'A';\n  else if (score >= 80) return 'B';\n  else if (score >= 70) return 'C';\n  else return 'F';\n}\nconsole.log(grade(85)); // 'B'` },
      { title: 'Loops', theory: 'for loops run a set number of times. while loops run while a condition is true. for...of iterates over arrays. for...in iterates over object keys. forEach is a cleaner array method.', challenge: 'Print numbers 1-10 using three different loop types.', snippet: `for (let i = 1; i <= 5; i++) console.log(i);\n\nconst fruits = ['apple', 'banana', 'mango'];\nfor (const fruit of fruits) console.log(fruit);\n\nfruits.forEach((fruit, index) => console.log(index, fruit));` },
      { title: 'Functions', theory: 'Functions are reusable blocks of code. Regular functions use the function keyword. Arrow functions use => and are more concise. Functions can have default parameters.', challenge: 'Write an arrow function that calculates the area of a circle.', snippet: `// Regular function\nfunction add(a, b) { return a + b; }\n\n// Arrow function\nconst multiply = (a, b) => a * b;\n\n// Default params\nconst greet = (name = 'Student') => \`Hello, \${name}!\`;` },
      { title: 'Arrays & Methods', theory: 'Arrays store ordered lists. Key methods: push/pop (add/remove end), shift/unshift (front), map (transform), filter (select), find (find one), reduce (aggregate), includes (check existence).', challenge: 'Use map and filter to transform an array of numbers.', snippet: `const nums = [1, 2, 3, 4, 5];\nconst doubled = nums.map(n => n * 2);   // [2,4,6,8,10]\nconst evens = nums.filter(n => n % 2 === 0); // [2,4]\nconst sum = nums.reduce((acc, n) => acc + n, 0); // 15` },
      { title: 'Objects', theory: 'Objects store key-value pairs. Access properties with dot notation (obj.key) or bracket notation (obj["key"]). Destructuring extracts properties. Spread (...) copies or merges objects.', challenge: 'Create a user object and destructure its properties.', snippet: `const user = { name: 'Alice', age: 25, role: 'student' };\n\n// Destructuring\nconst { name, age } = user;\n\n// Spread\nconst updated = { ...user, age: 26 };\n\n// Computed keys\nconst key = 'name';\nconsole.log(user[key]); // 'Alice'` },
      { title: 'DOM Manipulation', theory: 'The DOM (Document Object Model) is a tree of HTML elements that JS can access and modify. querySelector returns the first match. querySelectorAll returns all matches. innerHTML sets HTML content.', challenge: 'Select an element and change its text and color.', snippet: `const title = document.querySelector('#title');\ntitle.textContent = 'Hello World';\ntitle.style.color = '#2563eb';\n\n// Create and append\nconst btn = document.createElement('button');\nbtn.textContent = 'Click me';\ndocument.body.appendChild(btn);` },
      { title: 'Events & Listeners', theory: 'addEventListener attaches event handlers without overwriting existing ones. Common events: click, input, submit, keydown, mouseover, scroll. The event object contains info about what happened.', challenge: 'Add a click listener that counts button presses.', snippet: `let count = 0;\nconst btn = document.querySelector('#btn');\n\nbtn.addEventListener('click', (e) => {\n  count++;\n  console.log(\`Clicked \${count} times\`);\n  e.target.textContent = \`Count: \${count}\`;\n});` },
      { title: 'Promises & Async/Await', theory: 'Promises represent future values. .then() handles success, .catch() handles errors. async/await is cleaner syntax for promises. await pauses execution until the promise resolves.', challenge: 'Write an async function that simulates a data fetch.', snippet: `// Promise\nfetch('https://api.example.com/data')\n  .then(res => res.json())\n  .then(data => console.log(data))\n  .catch(err => console.error(err));\n\n// async/await\nasync function getData() {\n  try {\n    const res = await fetch('/api/data');\n    const data = await res.json();\n    return data;\n  } catch(err) { console.error(err); }\n}` },
      { title: 'Fetch API & Working with APIs', theory: 'fetch() makes HTTP requests. It returns a Promise. Always check res.ok before parsing. Pass an options object for POST requests with headers and body. JSON.stringify() converts objects to JSON strings.', challenge: 'Fetch data from a public API and display the result.', snippet: `async function getUser(id) {\n  const res = await fetch(\`https://jsonplaceholder.typicode.com/users/\${id}\`);\n  if (!res.ok) throw new Error('Failed');\n  const user = await res.json();\n  console.log(user.name);\n}` },
      { title: 'Local Storage', theory: 'localStorage stores key-value pairs in the browser persistently (survives page refresh). setItem saves data, getItem reads it, removeItem deletes it. Always JSON.stringify/parse for objects.', challenge: 'Save and retrieve a user object from localStorage.', snippet: `// Save\nconst user = { name: 'Alice', score: 100 };\nlocalStorage.setItem('user', JSON.stringify(user));\n\n// Read\nconst saved = JSON.parse(localStorage.getItem('user'));\nconsole.log(saved.name); // 'Alice'\n\n// Delete\nlocalStorage.removeItem('user');` },
      { title: 'Closures & Scope', theory: 'Scope determines where variables are accessible. Block scope (let/const), function scope, global scope. A closure is a function that remembers variables from its outer scope even after that scope has ended.', challenge: 'Create a counter using closures.', snippet: `function makeCounter() {\n  let count = 0; // private variable\n  return {\n    increment: () => ++count,\n    decrement: () => --count,\n    value: () => count\n  };\n}\nconst counter = makeCounter();\ncounter.increment(); // 1\ncounter.increment(); // 2` },
    ]
  },

  Python: {
    icon: 'fa-python',
    topics: [
      { title: 'What is Python', theory: 'Python is a high-level, readable programming language used for web development, data science, automation, and AI. It uses indentation instead of curly braces to define code blocks.', challenge: 'Write your first Python script that prints "Hello, World!".', snippet: `print("Hello, World!")\nprint("Welcome to T-Learn Pro")\n\n# This is a comment\nname = "Alice"\nprint(f"Hello, {name}!")` },
      { title: 'Variables & Data Types', theory: 'Python is dynamically typed — you don\'t declare types. Main types: int (whole numbers), float (decimals), str (text), bool (True/False), None. Use type() to check.', challenge: 'Create variables of each basic data type.', snippet: `age = 25            # int\nprice = 9.99        # float\nname = "Alice"      # str\nactive = True       # bool\ndata = None         # NoneType\n\nprint(type(age))    # <class 'int'>` },
      { title: 'Control Flow: If/Else', theory: 'Python uses if, elif, and else for conditional logic. Indentation (4 spaces) defines the code block. Comparison operators: ==, !=, >, <, >=, <=. Logical: and, or, not.', challenge: 'Write a function that classifies a temperature.', snippet: `temp = 35\n\nif temp >= 40:\n    print("Very hot")\nelif temp >= 25:\n    print("Warm")\nelif temp >= 15:\n    print("Cool")\nelse:\n    print("Cold")` },
      { title: 'Loops', theory: 'for loops iterate over sequences. range() generates numbers. while loops run while a condition is true. break exits the loop early. continue skips to the next iteration.', challenge: 'Print the first 10 square numbers using a for loop.', snippet: `# for loop\nfor i in range(1, 6):\n    print(i)\n\n# while loop\ncount = 0\nwhile count < 3:\n    print(count)\n    count += 1\n\n# Loop with break\nfor i in range(10):\n    if i == 5: break\n    print(i)` },
      { title: 'Functions', theory: 'Define functions with def. Parameters can have default values. Use return to send back a value. Lambda creates small anonymous functions. *args handles variable positional args, **kwargs handles keyword args.', challenge: 'Write a function with a default parameter.', snippet: `def greet(name, greeting="Hello"):\n    return f"{greeting}, {name}!"\n\nprint(greet("Alice"))           # Hello, Alice!\nprint(greet("Bob", "Hi"))       # Hi, Bob!\n\n# Lambda\nsquare = lambda x: x ** 2\nprint(square(5))                # 25` },
      { title: 'Lists', theory: 'Lists are ordered, mutable sequences. Access by index (0-based). Key methods: append(), extend(), insert(), remove(), pop(), sort(), reverse(). Slicing: list[start:end:step].', challenge: 'Create a list and use 5 different list methods.', snippet: `fruits = ["apple", "banana", "mango"]\nfruits.append("orange")       # add to end\nfruits.insert(1, "kiwi")      # insert at index\nfruits.remove("banana")       # remove by value\nprint(fruits[0])               # apple\nprint(fruits[-1])              # last item\nprint(fruits[1:3])             # slice` },
      { title: 'Dictionaries', theory: 'Dictionaries store key-value pairs (like JS objects). Keys must be unique and immutable. Access with dict[key] or dict.get(key). Iterate with .items(), .keys(), .values().', challenge: 'Create a student dictionary and access its values.', snippet: `student = {\n    "name": "Alice",\n    "grade": "A",\n    "score": 95\n}\n\nprint(student["name"])        # Alice\nprint(student.get("age", 0)) # 0 (default)\n\nfor key, value in student.items():\n    print(f"{key}: {value}")` },
      { title: 'Tuples & Sets', theory: 'Tuples are immutable lists (use parentheses). Good for fixed data. Sets are unordered collections with no duplicates. Use sets for membership testing (very fast) and removing duplicates.', challenge: 'Convert a list with duplicates to a set, then back to a list.', snippet: `# Tuple - immutable\npoint = (10, 20)\nx, y = point  # unpacking\n\n# Set - no duplicates\nnums = {1, 2, 2, 3, 3, 3}\nprint(nums)  # {1, 2, 3}\n\n# Remove duplicates from list\nclean = list(set([1, 2, 2, 3, 3]))` },
      { title: 'String Methods', theory: 'Strings are immutable in Python. Key methods: upper(), lower(), strip(), split(), join(), replace(), find(), startswith(), endswith(). f-strings are the modern way to format strings.', challenge: 'Clean and format a messy string input.', snippet: `text = "  Hello World  "\nprint(text.strip())           # "Hello World"\nprint(text.lower())           # "  hello world  "\nprint(text.split())           # ['Hello', 'World']\n\nname = "Alice"\nscore = 95\nprint(f"{name} scored {score}%")` },
      { title: 'File Handling', theory: 'Use open() to read/write files. Always use a with block — it closes the file automatically. Modes: "r" (read), "w" (write, overwrites), "a" (append), "r+" (read and write).', challenge: 'Write a program that saves and reads a list of names.', snippet: `# Write\nwith open("names.txt", "w") as f:\n    f.write("Alice\\nBob\\nCharlie")\n\n# Read\nwith open("names.txt", "r") as f:\n    names = f.readlines()\n    for name in names:\n        print(name.strip())` },
      { title: 'Error Handling', theory: 'try/except catches exceptions and prevents crashes. except can catch specific error types. else runs if no error occurred. finally always runs. raise creates custom exceptions.', challenge: 'Handle a division by zero error gracefully.', snippet: `def divide(a, b):\n    try:\n        result = a / b\n    except ZeroDivisionError:\n        return "Cannot divide by zero"\n    except TypeError:\n        return "Invalid types"\n    else:\n        return result\n    finally:\n        print("Operation attempted")\n\nprint(divide(10, 2))   # 5.0\nprint(divide(10, 0))   # error message` },
      { title: 'Classes & OOP', theory: 'Classes are blueprints for objects. __init__ is the constructor. self refers to the instance. Inheritance creates child classes that extend parents. Encapsulation hides internal details.', challenge: 'Create a Student class with name, grade, and a method.', snippet: `class Student:\n    def __init__(self, name, grade):\n        self.name = name\n        self.grade = grade\n\n    def introduce(self):\n        return f"I am {self.name}, grade {self.grade}"\n\n    def __repr__(self):\n        return f"Student({self.name})"\n\nalice = Student("Alice", "A")\nprint(alice.introduce())` },
      { title: 'List Comprehensions', theory: 'List comprehensions create lists in one line: [expression for item in iterable if condition]. They are faster and more Pythonic than for loops for creating lists.', challenge: 'Use a comprehension to get squares of even numbers 1-20.', snippet: `# Basic\nsquares = [x**2 for x in range(1, 6)]\n# [1, 4, 9, 16, 25]\n\n# With condition\nevens = [x for x in range(20) if x % 2 == 0]\n\n# Dict comprehension\nword_lengths = {word: len(word) for word in ["hi", "hello", "hey"]}` },
      { title: 'Modules & Imports', theory: 'import brings in external or standard library modules. from...import imports specific items. Common stdlib: os (file system), sys (system), json (JSON), datetime (dates), random (random numbers), math.', challenge: 'Import and use 3 standard library modules.', snippet: `import random\nimport json\nfrom datetime import datetime\n\nprint(random.randint(1, 100))\nprint(datetime.now().strftime("%Y-%m-%d"))\n\ndata = {"name": "Alice"}\njson_str = json.dumps(data)\nback = json.loads(json_str)` },
      { title: 'Working with APIs (requests)', theory: 'The requests library makes HTTP calls simple. requests.get() fetches data. .json() parses the response. Always check .status_code. Use params for query strings, json= for POST body.', challenge: 'Fetch and display data from a public API.', snippet: `import requests\n\n# GET request\nres = requests.get("https://jsonplaceholder.typicode.com/users/1")\nif res.status_code == 200:\n    user = res.json()\n    print(user["name"])\n\n# POST request\nnew_post = requests.post(\n    "https://jsonplaceholder.typicode.com/posts",\n    json={"title": "My Post", "body": "Content"}\n)` },
    ]
  },

};

// Make available globally
window.curriculumData = curriculumData;
